version = 0.1

[default.deploy.parameters]
stack_name = "bookstore-app-1"
resolve_s3 = true
s3_prefix = "bookstore-app-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "UserPoolId=\"us-east-1_wRsIhvNoQ\" UserPoolClientId=\"clccm3iqk4f9eaq7ru1r1q4f7\" SESFromEmail=\"temp@example.com\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
